import Link from "next/link";
import { IconArrowLeft } from "@tabler/icons-react";
import styles from "../legal.module.css";

export const metadata={title:"Privacy Policy | Meal05",description:"How Meal05 collects, uses and protects personal information."};
export default function PrivacyPage(){return <main className={styles.page}><div className={styles.shell}><Link className={styles.back} href="/"><IconArrowLeft size={17}/> Back to Meal05</Link><header className={styles.hero}><span className={styles.eyebrow}>Your information</span><h1>Privacy Policy</h1><p>This policy explains what Meal05 collects, why we use it, when we share it and the choices available to you.</p><span className={styles.updated}>Effective 1 July 2026</span></header><div className={styles.notice}>This operational draft reflects the current Meal05 application and should be reviewed by qualified Nigerian privacy counsel before public launch.</div><article className={styles.content}>
<section><h2>Contents</h2><p className={styles.contents}><a href="#scope">1. Scope</a><a href="#collect">2. Information collected</a><a href="#use">3. How we use it</a><a href="#share">4. Sharing</a><a href="#retention">5. Retention and security</a><a href="#rights">6. Your rights</a><a href="#cookies">7. Device storage</a><a href="#contact">8. Contact</a></p></section>
<section id="scope"><h2>1. Scope and responsibility</h2><p>This policy applies to Meal05 websites, accounts, shopping, delivery, support and waitlist services. “Meal05”, “we” and “us” refer to the operator of those services. It does not govern independent websites linked from Meal05.</p></section>
<section id="collect"><h2>2. Information we collect</h2><ul><li>Identity and contact details such as name, email address and phone number.</li><li>Account details, authentication records and communication preferences.</li><li>Delivery addresses, location preferences and delivery instructions.</li><li>Basket, order, substitution, refund and customer-support records.</li><li>Payment references and transaction status supplied by payment processors; we do not intentionally store full card details.</li><li>Ratings, reviews, searches, recently viewed products and interaction events.</li><li>Waitlist consent and campaign-attribution information.</li><li>Technical information such as IP address, device/browser data, security logs and necessary local-storage identifiers.</li></ul></section>
<section id="use"><h2>3. Why and how we use information</h2><p>We use information to create and secure accounts; process baskets, payments and orders; provide delivery and support; manage refunds and substitutions; remember preferences; improve catalogue quality; prevent fraud; maintain records; and meet legal obligations. Where required, processing is based on your consent, performance of our agreement, legal obligations or legitimate interests that do not override your rights.</p><p>Marketing messages are optional. You may withdraw marketing consent at any time without affecting service messages needed for an order or account.</p></section>
<section id="share"><h2>4. When information is shared</h2><p>We share only what is reasonably needed with service providers such as payment processors, hosting/database providers, email services, analytics/security providers, suppliers preparing an order and delivery partners completing it. We may also disclose information when required by law, to protect users and the service, or during a legitimate business reorganisation subject to appropriate safeguards.</p><p>We do not sell personal information. Some providers may process information outside Nigeria; where applicable, we use recognised transfer safeguards and contractual protections.</p></section>
<section id="retention"><h2>5. Retention and security</h2><p>We retain information only for as long as needed for the purposes described, including order fulfilment, support, accounting, fraud prevention, dispute handling and legal requirements. Retention periods vary by record type. We use access controls, encryption in transit, restricted administrative access and monitoring, but no online system can guarantee absolute security.</p></section>
<section id="rights"><h2>6. Your choices and rights</h2><p>Subject to applicable law, you may ask to access, correct, delete or restrict personal information; object to certain processing; withdraw consent; request portability where applicable; and complain about our handling of your information. We may verify your identity before acting and may retain records where legally required.</p><p>You may also complain to the Nigeria Data Protection Commission. Start a Meal05 request through our <Link href="/contact-us">contact page</Link>.</p></section>
<section id="cookies"><h2>7. Cookies, local storage and children</h2><p>Meal05 uses essential cookies or browser storage for sign-in, basket persistence, preferences, recent searches, security and service operation. Optional analytics or marketing technologies should be presented with appropriate choices before use. Meal05 is not directed to children who cannot legally consent to the service; a parent or guardian should place household orders for them.</p></section>
<section><h2>8. Policy changes</h2><p>We may update this policy as the service or law changes. The current version and effective date will remain available here, and material changes will be communicated reasonably.</p></section>
<section id="contact" className={styles.contact}><h2>Privacy questions</h2><p>Use the <Link href="/contact-us">Meal05 contact page</Link> and identify the request as a privacy matter. We will route it to the appropriate person.</p></section>
</article><p className={styles.footer}>Also read our <Link href="/terms">Terms and Conditions</Link>.</p></div></main>}
