create table if not exists public.order_idempotency_keys (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  idempotency_key text not null,
  request_fingerprint text,
  order_id integer references public.orders(id) on delete set null,
  status text not null default 'processing',
  response_status integer,
  response_body jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_idempotency_keys_status_check
    check (status in ('processing', 'completed', 'failed')),
  constraint order_idempotency_keys_key_not_blank
    check (length(trim(idempotency_key)) > 0),
  unique (user_id, idempotency_key)
);

comment on table public.order_idempotency_keys is
  'Server-side idempotency records for authenticated order creation requests.';
comment on column public.order_idempotency_keys.request_fingerprint is
  'Stable hash of the non-sensitive order intent used to reject key reuse with different payloads.';
comment on column public.order_idempotency_keys.response_body is
  'Sanitized successful order response replayed for duplicate requests with the same key.';

create index if not exists order_idempotency_keys_cleanup_idx
  on public.order_idempotency_keys (created_at)
  where status in ('completed', 'failed');

create index if not exists order_idempotency_keys_processing_idx
  on public.order_idempotency_keys (status, updated_at)
  where status = 'processing';

alter table public.order_idempotency_keys enable row level security;

drop trigger if exists order_idempotency_keys_touch_updated_at
  on public.order_idempotency_keys;

create or replace function public.order_idempotency_keys_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger order_idempotency_keys_touch_updated_at
  before update on public.order_idempotency_keys
  for each row execute function public.order_idempotency_keys_set_updated_at();

revoke all on function public.order_idempotency_keys_set_updated_at() from public;
grant execute on function public.order_idempotency_keys_set_updated_at() to service_role;

revoke all on table public.order_idempotency_keys from anon, authenticated;
revoke all on sequence public.order_idempotency_keys_id_seq from anon, authenticated;
grant all on table public.order_idempotency_keys to service_role;
grant all on sequence public.order_idempotency_keys_id_seq to service_role;
