-- refunds against orders
CREATE TABLE public.refunds (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     integer NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  amount       numeric NOT NULL CHECK (amount >= 0),
  reason       text,
  method       text NOT NULL DEFAULT 'wallet' CHECK (method IN ('wallet','original_payment','cash','bank_transfer')),
  status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','processed','rejected')),
  created_by   uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);
CREATE INDEX idx_refunds_order ON public.refunds(order_id);
COMMENT ON TABLE public.refunds IS 'Refunds issued against orders: amount, reason, and how money was returned (wallet, original payment, cash).';

-- cancellation tracking on orders
ALTER TABLE public.orders
  ADD COLUMN cancelled_at        timestamptz,
  ADD COLUMN cancellation_reason text;
COMMENT ON COLUMN public.orders.cancellation_reason IS 'Why the order was cancelled (set when status = cancelled).';

-- customer wallet / store-credit ledger
CREATE TABLE public.wallet_transactions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount     numeric NOT NULL,
  type       text NOT NULL CHECK (type IN ('credit','debit')),
  reason     text NOT NULL,
  order_id   integer REFERENCES public.orders(id) ON DELETE SET NULL,
  refund_id  bigint  REFERENCES public.refunds(id) ON DELETE SET NULL,
  note       text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_wallet_tx_user ON public.wallet_transactions(user_id);
COMMENT ON TABLE public.wallet_transactions IS 'Customer wallet / store-credit ledger. Positive amount = credit, negative = debit; balance = sum per user.';

CREATE VIEW public.vw_wallet_balances WITH (security_invoker = on) AS
SELECT user_id, COALESCE(sum(amount),0) AS balance, max(created_at) AS last_activity
FROM public.wallet_transactions GROUP BY user_id;
COMMENT ON VIEW public.vw_wallet_balances IS 'Current wallet/store-credit balance per customer (sum of wallet_transactions).';

-- RLS
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
CREATE POLICY refunds_select_own ON public.refunds FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.user_id = (SELECT auth.uid())) OR public.is_admin_user());
CREATE POLICY refunds_admin_all ON public.refunds FOR ALL TO authenticated
  USING (public.is_admin_user()) WITH CHECK (public.is_admin_user());

ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY wallet_select_own ON public.wallet_transactions FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()) OR public.is_admin_user());
CREATE POLICY wallet_admin_all ON public.wallet_transactions FOR ALL TO authenticated
  USING (public.is_admin_user()) WITH CHECK (public.is_admin_user());
