begin;

create table if not exists public.product_mode_settings (
  product_id bigint not null references public.products(id) on delete cascade,
  shopping_mode text not null check (shopping_mode in ('household', 'business')),
  is_visible boolean not null default true,
  requires_quote boolean not null default false,
  purchasing_conditions text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_id, shopping_mode)
);

create table if not exists public.product_variant_mode_settings (
  variant_id bigint not null references public.product_variants(id) on delete cascade,
  shopping_mode text not null check (shopping_mode in ('household', 'business')),
  price numeric check (price is null or price >= 0),
  is_visible boolean not null default true,
  min_quantity numeric check (min_quantity is null or min_quantity > 0),
  max_quantity numeric check (max_quantity is null or max_quantity > 0),
  step_quantity numeric check (step_quantity is null or step_quantity > 0),
  packaging_label text,
  availability_mode text not null default 'standard' check (availability_mode in ('standard', 'request', 'unavailable')),
  supplier_confirmation_required boolean not null default false,
  direct_checkout_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (variant_id, shopping_mode),
  constraint product_variant_mode_quantity_bounds check (
    min_quantity is null or max_quantity is null or min_quantity <= max_quantity
  )
);

alter table public.cart_items
  add column if not exists shopping_mode text not null default 'household',
  add column if not exists quote_only boolean not null default false,
  add column if not exists supplier_confirmation_required boolean not null default false;

alter table public.cart_items drop constraint if exists cart_items_shopping_mode_check;
alter table public.cart_items add constraint cart_items_shopping_mode_check
  check (shopping_mode in ('household', 'business'));

drop index if exists public.cart_items_user_variant_unique;
drop index if exists public.cart_items_user_variant_unique_idx;
drop index if exists public.cart_items_user_id_variant_id_key;
alter table public.cart_items drop constraint if exists cart_items_user_id_variant_id_key;
create unique index if not exists cart_items_user_mode_variant_unique
  on public.cart_items(user_id, shopping_mode, variant_id);

alter table public.orders
  add column if not exists shopping_mode text not null default 'household',
  add column if not exists order_source text not null default 'website',
  add column if not exists business_name text,
  add column if not exists business_contact_name text,
  add column if not exists business_phone text,
  add column if not exists business_address text;

alter table public.orders drop constraint if exists orders_shopping_mode_check;
alter table public.orders add constraint orders_shopping_mode_check
  check (shopping_mode in ('household', 'business'));
alter table public.orders drop constraint if exists orders_order_source_check;
alter table public.orders add constraint orders_order_source_check
  check (order_source in ('website', 'whatsapp', 'phone', 'admin'));

create table if not exists public.business_quote_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  reference text not null unique,
  status text not null default 'new' check (status in ('new', 'reviewing', 'quoted', 'accepted', 'declined', 'closed')),
  business_name text not null,
  contact_name text not null,
  email text not null,
  phone text not null,
  delivery_address text not null,
  notes text,
  admin_notes text,
  quoted_total numeric check (quoted_total is null or quoted_total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_quote_items (
  id bigint generated by default as identity primary key,
  quote_request_id bigint not null references public.business_quote_requests(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  variant_id bigint references public.product_variants(id) on delete set null,
  product_name text not null,
  variant_name text,
  quantity numeric not null check (quantity > 0),
  requested_unit text,
  configured_unit_price numeric check (configured_unit_price is null or configured_unit_price >= 0),
  supplier_confirmation_required boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists business_quote_requests_user_created_idx
  on public.business_quote_requests(user_id, created_at desc);
create index if not exists business_quote_requests_status_created_idx
  on public.business_quote_requests(status, created_at desc);
create index if not exists business_quote_items_request_idx
  on public.business_quote_items(quote_request_id);

alter table public.product_mode_settings enable row level security;
alter table public.product_variant_mode_settings enable row level security;
alter table public.business_quote_requests enable row level security;
alter table public.business_quote_items enable row level security;

drop policy if exists product_mode_settings_public_read on public.product_mode_settings;
create policy product_mode_settings_public_read on public.product_mode_settings
  for select to anon, authenticated using (true);
drop policy if exists product_mode_settings_admin_all on public.product_mode_settings;
create policy product_mode_settings_admin_all on public.product_mode_settings
  for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

drop policy if exists product_variant_mode_settings_public_read on public.product_variant_mode_settings;
create policy product_variant_mode_settings_public_read on public.product_variant_mode_settings
  for select to anon, authenticated using (true);
drop policy if exists product_variant_mode_settings_admin_all on public.product_variant_mode_settings;
create policy product_variant_mode_settings_admin_all on public.product_variant_mode_settings
  for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

drop policy if exists business_quote_requests_owner_read on public.business_quote_requests;
create policy business_quote_requests_owner_read on public.business_quote_requests
  for select to authenticated using (user_id = (select auth.uid()) or public.is_admin_user());
drop policy if exists business_quote_requests_admin_all on public.business_quote_requests;
create policy business_quote_requests_admin_all on public.business_quote_requests
  for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

drop policy if exists business_quote_items_owner_read on public.business_quote_items;
create policy business_quote_items_owner_read on public.business_quote_items
  for select to authenticated using (
    exists (
      select 1 from public.business_quote_requests request
      where request.id = quote_request_id
        and (request.user_id = (select auth.uid()) or public.is_admin_user())
    )
  );
drop policy if exists business_quote_items_admin_all on public.business_quote_items;
create policy business_quote_items_admin_all on public.business_quote_items
  for all to authenticated using (public.is_admin_user()) with check (public.is_admin_user());

revoke insert, update, delete on public.product_mode_settings from anon;
revoke insert, update, delete on public.product_variant_mode_settings from anon;
revoke insert, update, delete on public.business_quote_requests from anon, authenticated;
revoke insert, update, delete on public.business_quote_items from anon, authenticated;

comment on table public.product_mode_settings is 'Per-shopping-mode product visibility and purchasing rules.';
comment on table public.product_variant_mode_settings is 'Admin-configured per-mode variant prices, quantities and fulfilment conditions.';
comment on table public.business_quote_requests is 'Business quotation requests. Creating one never creates an order or payment.';

commit;
