alter table public.products
  add column if not exists is_price_volatile boolean not null default false;

comment on column public.products.is_price_volatile is
  'Flags products whose market/farm-gate price changes frequently and should appear in the fast admin price update workflow.';

create table if not exists public.variant_price_history (
  id bigint generated by default as identity primary key,
  variant_id bigint not null references public.product_variants(id) on delete cascade,
  old_price numeric not null,
  new_price numeric not null,
  changed_by uuid,
  changed_at timestamptz not null default now()
);

create index if not exists variant_price_history_variant_changed_at_idx
  on public.variant_price_history (variant_id, changed_at desc);

comment on table public.variant_price_history is
  'Audit log for every admin product variant price change.';
comment on column public.variant_price_history.changed_by is
  'Supabase auth user id for the admin who changed the price.';

alter table public.variant_price_history enable row level security;

drop policy if exists "Service role manages variant price history" on public.variant_price_history;
create policy "Service role manages variant price history"
  on public.variant_price_history
  for all
  to service_role
  using (true)
  with check (true);

grant all on table public.variant_price_history to service_role;
