-- pickup locations (e.g. the Meal05 hub)
CREATE TABLE public.pickup_locations (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  address      text NOT NULL,
  city         text NOT NULL DEFAULT 'Ibadan',
  phone        text,
  hours        text,
  instructions text,
  is_active    boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.pickup_locations IS 'Physical locations where customers can collect orders (e.g. the Meal05 hub).';

-- let orders be delivery OR pickup
ALTER TABLE public.orders
  ADD COLUMN fulfillment_type   text NOT NULL DEFAULT 'delivery'
             CHECK (fulfillment_type IN ('delivery','pickup')),
  ADD COLUMN pickup_location_id bigint REFERENCES public.pickup_locations(id) ON DELETE SET NULL;
COMMENT ON COLUMN public.orders.fulfillment_type IS 'How the order is fulfilled: delivery or pickup.';
COMMENT ON COLUMN public.orders.pickup_location_id IS 'When fulfillment_type = pickup, the chosen pickup location.';

-- delivery zones with per-zone fees, for checkout validation
CREATE TABLE public.delivery_zones (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL UNIQUE,
  city         text NOT NULL DEFAULT 'Ibadan',
  delivery_fee numeric NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
  min_order    numeric CHECK (min_order IS NULL OR min_order >= 0),
  eta_note     text,
  is_active    boolean NOT NULL DEFAULT true,
  sort_order   integer,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.delivery_zones IS 'Delivery areas with per-zone fees and minimums, used for checkout zone validation.';
COMMENT ON COLUMN public.delivery_zones.delivery_fee IS 'Delivery fee for this zone (NGN).';
COMMENT ON COLUMN public.delivery_zones.min_order IS 'Optional minimum order subtotal required to deliver to this zone.';

-- correct the wrong default service zone
ALTER TABLE public.delivery_settings ALTER COLUMN service_zones SET DEFAULT ARRAY['Ibadan']::text[];
UPDATE public.delivery_settings
SET service_zones = ARRAY['Ibadan']::text[], updated_at = now()
WHERE service_zones IS NULL OR service_zones = ARRAY['Lagos']::text[];
