
-- 1. classify products: fresh (daily-menu driven) vs staple (always-on from stock)
ALTER TABLE public.products
  ADD COLUMN sourcing_type text NOT NULL DEFAULT 'staple'
  CHECK (sourcing_type IN ('fresh','staple'));
COMMENT ON COLUMN public.products.sourcing_type IS 'fresh = perishable, shown only when on the day''s locked menu, sourced post-order; staple = always available from stock_ledger. Default staple preserves current behaviour.';

-- 2. daily menu header: one per day, with lock event + audit
CREATE TABLE public.daily_menus (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_date  date NOT NULL UNIQUE,
  status     text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','locked','closed')),
  locked_at  timestamptz,
  locked_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.daily_menus IS 'One row per trading day. status draft -> locked (frozen at the 4 PM cutoff) -> closed. Drives which fresh items the storefront shows that day.';
COMMENT ON COLUMN public.daily_menus.locked_by IS 'Admin who locked the menu (audit trail).';

-- 3. daily menu lines: per-variant availability, today's price, caps
CREATE TABLE public.daily_menu_items (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_menu_id bigint NOT NULL REFERENCES public.daily_menus(id) ON DELETE CASCADE,
  variant_id    bigint NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  is_available  boolean NOT NULL DEFAULT true,
  price_today   numeric CHECK (price_today IS NULL OR price_today >= 0),
  cap_qty       integer CHECK (cap_qty IS NULL OR cap_qty >= 0),
  sold_qty      integer NOT NULL DEFAULT 0 CHECK (sold_qty >= 0),
  note          text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (daily_menu_id, variant_id)
);
COMMENT ON TABLE public.daily_menu_items IS 'Items on a given day''s menu, with that day''s availability, price, and optional quantity cap.';
COMMENT ON COLUMN public.daily_menu_items.price_today IS 'Market price set for this item today. Falls back to the variant base price when null.';
COMMENT ON COLUMN public.daily_menu_items.cap_qty IS 'Optional max units offered today; sold_qty tracks against it.';
CREATE INDEX idx_daily_menu_items_menu    ON public.daily_menu_items(daily_menu_id);
CREATE INDEX idx_daily_menu_items_variant ON public.daily_menu_items(variant_id);

-- 4. auto-stamp lock time + updated_at
CREATE OR REPLACE FUNCTION public.set_daily_menu_locked_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  IF NEW.status = 'locked' AND OLD.status IS DISTINCT FROM 'locked' AND NEW.locked_at IS NULL THEN
    NEW.locked_at := now();
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_daily_menu_lock
  BEFORE UPDATE ON public.daily_menus
  FOR EACH ROW EXECUTE FUNCTION public.set_daily_menu_locked_at();

-- 5. storefront helper: today's live fresh menu (Africa/Lagos), effective price resolved
CREATE VIEW public.v_todays_menu WITH (security_invoker = on) AS
SELECT
  dm.menu_date, dm.status AS menu_status,
  p.id AS product_id, p.name AS product, c.name AS category,
  v.id AS variant_id, v.name AS variant, v.unit,
  COALESCE(i.price_today, v.price) AS effective_price,
  i.price_today, v.price AS base_price,
  i.cap_qty, i.sold_qty,
  CASE WHEN i.cap_qty IS NULL THEN NULL ELSE GREATEST(i.cap_qty - i.sold_qty, 0) END AS remaining_today
FROM public.daily_menus dm
JOIN public.daily_menu_items i ON i.daily_menu_id = dm.id
JOIN public.product_variants v ON v.id = i.variant_id
JOIN public.products p ON p.id = v.product_id
LEFT JOIN public.product_categories c ON c.id = p.category_id
WHERE dm.menu_date = (now() AT TIME ZONE 'Africa/Lagos')::date
  AND i.is_available;
COMMENT ON VIEW public.v_todays_menu IS 'Today''s live fresh menu (Africa/Lagos date): available items with effective price and remaining quantity.';
;
