
-- substitutions on order line items
ALTER TABLE public.order_items
  ADD COLUMN substituted_variant_id bigint REFERENCES public.product_variants(id) ON DELETE SET NULL,
  ADD COLUMN substitution_status text NOT NULL DEFAULT 'none' CHECK (substitution_status IN ('none','proposed','accepted','rejected')),
  ADD COLUMN substitution_note text;
COMMENT ON COLUMN public.order_items.substituted_variant_id IS 'If the ordered item was out of stock, the variant actually supplied instead.';

-- order-level preferences, notes, and tax
ALTER TABLE public.orders
  ADD COLUMN allow_substitutions   boolean NOT NULL DEFAULT true,
  ADD COLUMN customer_note         text,
  ADD COLUMN delivery_instructions text,
  ADD COLUMN tax_amount            numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
  ADD COLUMN tax_rate              numeric CHECK (tax_rate IS NULL OR tax_rate >= 0);
COMMENT ON COLUMN public.orders.allow_substitutions IS 'Customer consent to receive a substitute if an item is out of stock.';
COMMENT ON COLUMN public.orders.delivery_instructions IS 'Customer instructions for the rider, e.g. call at the gate.';
COMMENT ON COLUMN public.orders.tax_amount IS 'VAT/tax charged on the order (NGN).';

-- proof of delivery
ALTER TABLE public.deliveries
  ADD COLUMN delivery_code   text,
  ADD COLUMN recipient_name  text,
  ADD COLUMN proof_photo_url text,
  ADD COLUMN proof_note      text;
COMMENT ON COLUMN public.deliveries.delivery_code IS 'One-time code the customer gives the rider to confirm handover.';
COMMENT ON COLUMN public.deliveries.proof_photo_url IS 'Photo captured as proof of delivery.';

-- written reviews
ALTER TABLE public.product_ratings
  ADD COLUMN title text,
  ADD COLUMN review text,
  ADD COLUMN is_approved boolean NOT NULL DEFAULT true;
COMMENT ON COLUMN public.product_ratings.review IS 'Optional written review accompanying the star rating.';
COMMENT ON COLUMN public.product_ratings.is_approved IS 'Moderation flag; false hides the review from the public.';
-- honour moderation in the public read policy
DROP POLICY IF EXISTS product_ratings_public_read ON public.product_ratings;
CREATE POLICY product_ratings_public_read ON public.product_ratings FOR SELECT TO public
  USING (is_approved = true OR public.is_admin_user());

-- local/Yoruba names + search keywords
ALTER TABLE public.products
  ADD COLUMN local_name      text,
  ADD COLUMN search_keywords text;
COMMENT ON COLUMN public.products.local_name IS 'Local/Yoruba name(s) for the item, e.g. efo, ata, to aid search.';
COMMENT ON COLUMN public.products.search_keywords IS 'Extra search terms/synonyms for discovery.';

-- per-order status timeline
CREATE TABLE public.order_status_history (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   integer NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  from_status text,
  to_status   text NOT NULL,
  changed_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_order_status_history_order ON public.order_status_history(order_id);
COMMENT ON TABLE public.order_status_history IS 'Timeline of status changes per order, for support and analytics.';

ALTER TABLE public.order_status_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY osh_select_own ON public.order_status_history FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.user_id = (SELECT auth.uid())) OR public.is_admin_user());
CREATE POLICY osh_admin_all ON public.order_status_history FOR ALL TO authenticated
  USING (public.is_admin_user()) WITH CHECK (public.is_admin_user());
;
