
-- view depends on stock_movements_v2; drop now, rebuild on the new ledger below
DROP VIEW IF EXISTS public.restock_log_v2;

-- the single unified stock ledger
CREATE TABLE public.stock_ledger (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id bigint NOT NULL REFERENCES public.product_variants(id) ON DELETE CASCADE,
  change_qty integer NOT NULL,
  reason     text NOT NULL,
  source     text,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_stock_ledger_variant ON public.stock_ledger(variant_id);

COMMENT ON TABLE public.stock_ledger IS 'Unified stock movement ledger: every change to variant stock (sales, restocks, adjustments). Replaces the 5 legacy stock/restock tables.';
COMMENT ON COLUMN public.stock_ledger.change_qty IS 'Signed quantity change: positive = stock in, negative = stock out.';
COMMENT ON COLUMN public.stock_ledger.reason IS 'Why the change happened, e.g. sale, restock, adjustment.';
COMMENT ON COLUMN public.stock_ledger.source IS 'Optional origin, e.g. order id, admin, system.';

-- migrate the variant-based history from the two movement tables
INSERT INTO public.stock_ledger (variant_id, change_qty, reason, source, note, created_at)
SELECT variant_id, change_quantity, reason, NULL, note, created_at FROM public.stock_movements;

INSERT INTO public.stock_ledger (variant_id, change_qty, reason, source, note, created_at)
SELECT variant_id, change_qty, reason, source, note, created_at FROM public.stock_movements_v2;

-- retire the 5 legacy tables (all rows preserved in the backup schema)
DROP TABLE public.stock_movements;
DROP TABLE public.stock_movements_v2;
DROP TABLE public.inventory_movements;
DROP TABLE public.restock_log;
DROP TABLE public.stock_deduction_log;

-- rebuild the convenience view on the new ledger
CREATE VIEW public.restock_log_v2 WITH (security_invoker = on) AS
SELECT id, variant_id, change_qty AS quantity, source AS restocked_by, created_at AS restocked_at
FROM public.stock_ledger
WHERE reason = 'restock';
;
