-- Radius-based delivery serviceability for the Akala Express launch hub.
-- Coordinates are WGS84 decimal degrees. Distances are calculated in metres.

do $$
declare
  legacy_function record;
begin
  for legacy_function in
    select p.oid::regprocedure as signature
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = 'resolve_delivery_zone'
      and p.pronargs = 2
  loop
    execute format('drop function %s', legacy_function.signature);
  end loop;
end
$$;

delete from public.delivery_zones
where lower(name) in ('ibadan core', 'ibadan core (5km)', 'ibadan core 5km');

alter table public.delivery_zones drop column if exists radius_km;

do $$
begin
  if exists (
    select 1 from public.delivery_zones group by name having count(*) > 1
  ) then
    raise exception 'Duplicate delivery_zones.name values must be resolved before applying the radius-zone migration.';
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_index i
    join pg_class t on t.oid = i.indrelid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and t.relname = 'delivery_zones'
      and i.indisunique
      and i.indnatts = 1
      and pg_get_indexdef(i.indexrelid) ~ '\(name\)'
  ) then
    create unique index delivery_zones_name_unique_idx on public.delivery_zones (name);
  end if;
end
$$;

alter table public.delivery_zones
  add column if not exists zone_type text not null default 'radius',
  add column if not exists center_lat double precision,
  add column if not exists center_lng double precision,
  add column if not exists radius_m integer,
  add column if not exists priority integer not null default 100;

alter table public.delivery_zones drop constraint if exists delivery_zones_zone_type_valid;
alter table public.delivery_zones add constraint delivery_zones_zone_type_valid
  check (zone_type in ('radius', 'polygon'));
alter table public.delivery_zones drop constraint if exists delivery_zones_center_lat_valid;
alter table public.delivery_zones add constraint delivery_zones_center_lat_valid
  check (center_lat is null or center_lat between -90 and 90);
alter table public.delivery_zones drop constraint if exists delivery_zones_center_lng_valid;
alter table public.delivery_zones add constraint delivery_zones_center_lng_valid
  check (center_lng is null or center_lng between -180 and 180);
alter table public.delivery_zones drop constraint if exists delivery_zones_radius_valid;
alter table public.delivery_zones add constraint delivery_zones_radius_valid
  check (radius_m is null or radius_m > 0);

comment on column public.delivery_zones.center_lat is 'WGS84 latitude of a radius-zone centre.';
comment on column public.delivery_zones.center_lng is 'WGS84 longitude of a radius-zone centre.';
comment on column public.delivery_zones.radius_m is 'Maximum straight-line service radius in metres.';
comment on column public.delivery_zones.priority is 'Lower values win when multiple active zones overlap.';

create index if not exists delivery_zones_radius_lookup_idx
  on public.delivery_zones (market_id, is_active, zone_type, priority);

create table if not exists public.delivery_zone_areas (
  id bigint generated by default as identity primary key,
  zone_id bigint not null references public.delivery_zones(id) on delete cascade,
  name text not null,
  slug text not null,
  area_type text not null default 'locality'
    check (area_type in ('lga', 'ward', 'locality', 'estate', 'landmark')),
  lga_name text,
  aliases text[] not null default '{}',
  display_priority integer not null default 100,
  is_featured boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (zone_id, slug)
);

comment on table public.delivery_zone_areas is 'Ranked customer-facing area names associated with geometric delivery zones; not authoritative geometry.';
create index if not exists delivery_zone_areas_display_idx
  on public.delivery_zone_areas (zone_id, is_active, is_featured desc, display_priority, name);

alter table public.delivery_zone_areas enable row level security;
drop policy if exists delivery_zone_areas_public_read on public.delivery_zone_areas;
create policy delivery_zone_areas_public_read on public.delivery_zone_areas
  for select to public using (is_active = true);
drop policy if exists delivery_zone_areas_admin_all on public.delivery_zone_areas;
create policy delivery_zone_areas_admin_all on public.delivery_zone_areas
  for all to authenticated using (is_admin_user()) with check (is_admin_user());

alter table public.user_addresses
  add column if not exists latitude double precision,
  add column if not exists longitude double precision,
  add column if not exists formatted_address text,
  add column if not exists provider_place_id text,
  add column if not exists geocoding_provider text,
  add column if not exists delivery_zone_id bigint references public.delivery_zones(id) on delete set null,
  add column if not exists location_validated_at timestamptz;

alter table public.orders
  add column if not exists delivery_latitude double precision,
  add column if not exists delivery_longitude double precision,
  add column if not exists delivery_zone_id bigint references public.delivery_zones(id) on delete set null,
  add column if not exists delivery_zone_name text;

alter table public.waitlist
  add column if not exists requested_latitude double precision,
  add column if not exists requested_longitude double precision,
  add column if not exists requested_address text;

create or replace function public.resolve_delivery_zone(
  p_lat double precision,
  p_lng double precision,
  p_market_id uuid default public.default_market_id()
)
returns table (
  zone_id bigint,
  zone_name text,
  delivery_fee numeric,
  min_order numeric,
  eta_note text,
  distance_m double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    z.id,
    z.name,
    z.delivery_fee,
    z.min_order,
    z.eta_note,
    d.distance_m
  from public.delivery_zones z
  cross join lateral (
    select 6371000.0 * 2.0 * asin(
      least(1.0, sqrt(
        power(sin(radians(p_lat - z.center_lat) / 2.0), 2) +
        cos(radians(z.center_lat)) * cos(radians(p_lat)) *
        power(sin(radians(p_lng - z.center_lng) / 2.0), 2)
      ))
    ) as distance_m
  ) d
  where z.market_id = p_market_id
    and z.is_active = true
    and z.zone_type = 'radius'
    and z.center_lat is not null
    and z.center_lng is not null
    and z.radius_m is not null
    and p_lat between -90 and 90
    and p_lng between -180 and 180
    and d.distance_m <= z.radius_m
  order by z.priority asc, d.distance_m asc, z.id asc
  limit 1;
$$;

comment on function public.resolve_delivery_zone(double precision, double precision, uuid)
  is 'Returns the highest-priority active radius zone containing a WGS84 point, or no row.';
grant execute on function public.resolve_delivery_zone(double precision, double precision, uuid) to anon, authenticated, service_role;

insert into public.delivery_zones (
  name, city, delivery_fee, min_order, eta_note, is_active, sort_order,
  market_id, zone_type, center_lat, center_lng, radius_m, priority
)
values (
  'Akala Express Launch Zone', 'Ibadan', 1500, null,
  'Same-day delivery within the Akala Express launch area', true, 1,
  public.default_market_id(), 'radius', 7.342134, 3.847802, 5000, 1
)
on conflict (name) do update set
  city = excluded.city,
  market_id = excluded.market_id,
  zone_type = excluded.zone_type,
  center_lat = excluded.center_lat,
  center_lng = excluded.center_lng,
  radius_m = excluded.radius_m,
  priority = excluded.priority,
  is_active = true,
  updated_at = now();

insert into public.delivery_zone_areas (zone_id, name, slug, area_type, lga_name, aliases, display_priority, is_featured)
select z.id, a.name, a.slug, a.area_type, a.lga_name, a.aliases, a.display_priority, a.is_featured
from public.delivery_zones z
cross join (values
  ('Elebu', 'elebu', 'locality', null, array['Elebu, Ibadan'], 10, true),
  ('Akala Express', 'akala-express', 'locality', null, array['Alao Akala Expressway', 'Akala Express Way'], 20, true),
  ('Oluyole Estate', 'oluyole-estate', 'estate', 'Ibadan South-West', array['Oluyole Main Estate'], 30, true),
  ('New Garage', 'new-garage', 'locality', null, array['New Garage, Ibadan'], 40, true),
  ('Challenge', 'challenge', 'locality', null, array['Challenge, Ibadan', 'Orita Challenge'], 50, true),
  ('Ring Road', 'ring-road', 'locality', 'Ibadan South-West', array['MKO Abiola Way', 'Ring Road, Ibadan'], 60, true),
  ('Odo-Ona', 'odo-ona', 'locality', null, array['Odo Ona', 'Odo-Ona Elewe'], 70, false)
) as a(name, slug, area_type, lga_name, aliases, display_priority, is_featured)
where z.name = 'Akala Express Launch Zone'
on conflict (zone_id, slug) do update set
  name = excluded.name,
  area_type = excluded.area_type,
  lga_name = excluded.lga_name,
  aliases = excluded.aliases,
  display_priority = excluded.display_priority,
  is_featured = excluded.is_featured,
  is_active = true,
  updated_at = now();

delete from public.delivery_zone_areas a
using public.delivery_zones z
where a.zone_id = z.id
  and z.name = 'Akala Express Launch Zone'
  and a.slug in ('apata', 'omi-adio', 'akufo', 'awotan', 'apete');

notify pgrst, 'reload schema';;
