create table if not exists private.product_price_snapshots (
  id bigint generated by default as identity primary key,
  label text not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);

comment on table private.product_price_snapshots is 'Internal reversible snapshots of product variant pricing/state; not exposed through the public Data API.';
