create table if not exists public.supplier_product_quotes (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quote_label text not null,
  source_pack_quantity numeric not null check (source_pack_quantity > 0),
  source_pack_unit text not null,
  unit_size numeric null check (unit_size is null or unit_size > 0),
  unit_size_unit text null,
  quoted_cost numeric not null check (quoted_cost >= 0),
  min_order_packs numeric not null default 1 check (min_order_packs > 0),
  is_confirmed boolean not null default true,
  is_current boolean not null default true,
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (supplier_id, product_id, quote_label, min_order_packs)
);

comment on table public.supplier_product_quotes is 'Supplier-specific source-pack quotations, including carton/bag quantities, pack sizes and quantity-tier pricing.';

alter table public.supplier_product_quotes enable row level security;
create index if not exists supplier_product_quotes_supplier_idx on public.supplier_product_quotes(supplier_id);
create index if not exists supplier_product_quotes_product_idx on public.supplier_product_quotes(product_id);;
