create table if not exists public.order_idempotency_keys (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  idempotency_key text not null,
  request_fingerprint text,
  order_id integer,
  status text not null default 'processing',
  response_status integer,
  response_body jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_idempotency_keys_user_key_unique unique (user_id, idempotency_key),
  constraint order_idempotency_keys_user_id_fkey
    foreign key (user_id) references auth.users(id) on delete cascade,
  constraint order_idempotency_keys_order_id_fkey
    foreign key (order_id) references public.orders(id) on delete set null
);

create index if not exists order_idempotency_keys_created_at_idx
  on public.order_idempotency_keys (created_at);

create index if not exists order_idempotency_keys_order_id_idx
  on public.order_idempotency_keys (order_id)
  where order_id is not null;

alter table public.order_idempotency_keys enable row level security;

revoke all on table public.order_idempotency_keys from anon, authenticated;
revoke all on sequence public.order_idempotency_keys_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.order_idempotency_keys to service_role;
grant usage, select on sequence public.order_idempotency_keys_id_seq to service_role;

comment on table public.order_idempotency_keys is
  'Server-only persistent idempotency reservations and replay responses for order creation.';;
