create table if not exists public.payment_provider_settings (
  id bigint generated by default as identity primary key,
  code text not null unique,
  display_name text not null,
  method_type text not null,
  is_active boolean not null default false,
  is_recommended boolean not null default false,
  checkout_enabled boolean not null default false,
  wallet_topup_enabled boolean not null default false,
  display_order integer not null default 100,
  bank_name text,
  account_name text,
  account_number text,
  logo_url text,
  customer_notice text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_provider_settings_method_type_check
    check (method_type in ('bank_transfer', 'gateway')),
  constraint payment_provider_settings_recommended_active_check
    check (not is_recommended or is_active),
  constraint payment_provider_settings_display_order_check
    check (display_order >= 0)
);

create unique index if not exists payment_provider_settings_code_uidx
  on public.payment_provider_settings(code);

create unique index if not exists payment_provider_settings_one_recommended_transfer_uidx
  on public.payment_provider_settings((is_recommended))
  where is_recommended = true and method_type = 'bank_transfer';

alter table public.payment_provider_settings enable row level security;
revoke all on table public.payment_provider_settings from anon, authenticated;
grant all on table public.payment_provider_settings to service_role;

insert into public.payment_provider_settings (
  code,
  display_name,
  method_type,
  is_active,
  is_recommended,
  checkout_enabled,
  wallet_topup_enabled,
  display_order,
  bank_name,
  account_name,
  account_number,
  logo_url,
  customer_notice
) values
  (
    'moniepoint_transfer',
    'Moniepoint Transfer',
    'bank_transfer',
    false,
    false,
    false,
    false,
    1,
    null,
    null,
    null,
    null,
    'Transfer the exact amount shown. Confirm the bank and account details before sending. Include the Meal05 payment reference in your transfer narration where your bank supports it. After payment, select “I’ve sent the money” and submit your transfer details. Payment remains pending until Meal05 confirms receipt. Do not make another transfer for the same reference unless Meal05 support asks you to.'
  ),
  (
    'opay_transfer',
    'OPay Transfer',
    'bank_transfer',
    false,
    false,
    false,
    false,
    2,
    null,
    null,
    null,
    null,
    'The Meal05 OPay transfer option is unavailable for now.'
  ),
  (
    'paystack',
    'Card, USSD and Paystack',
    'gateway',
    false,
    false,
    false,
    false,
    3,
    null,
    null,
    null,
    null,
    'This payment option will become available after Meal05 activates gateway settlement for daily operations.'
  )
on conflict (code) do update
set display_name = excluded.display_name,
    method_type = excluded.method_type,
    display_order = excluded.display_order,
    customer_notice = excluded.customer_notice,
    updated_at = now();

notify pgrst, 'reload schema';;
