
CREATE TABLE public.notifications (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid    REFERENCES auth.users(id) ON DELETE SET NULL,
  order_id   integer REFERENCES public.orders(id) ON DELETE SET NULL,
  channel    text NOT NULL CHECK (channel IN ('whatsapp','sms','email','push','in_app')),
  event      text,
  recipient  text,
  subject    text,
  body       text,
  status     text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','delivered','failed','read')),
  error      text,
  sent_at    timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_user  ON public.notifications(user_id);
CREATE INDEX idx_notifications_order ON public.notifications(order_id);
COMMENT ON TABLE public.notifications IS 'Log of messages sent to customers (WhatsApp/SMS/email/push) with delivery status. Drives confirmations and dispatch alerts.';
COMMENT ON COLUMN public.notifications.event IS 'Event/template key, e.g. order_received, out_for_delivery, payment_confirmed.';

-- RLS: customers see their own, admins see all
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY notifications_select_own ON public.notifications FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()) OR public.is_admin_user());
CREATE POLICY notifications_admin_all ON public.notifications FOR ALL TO authenticated
  USING (public.is_admin_user()) WITH CHECK (public.is_admin_user());
;
