create table if not exists public.local_measurement_units (
  code text primary key,
  display_name text not null,
  congo_multiplier numeric(10,4) not null check (congo_multiplier > 0),
  tin_cup_count numeric(10,2) not null check (tin_cup_count > 0),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.local_measurement_units is
  'Reusable Nigerian local dry-goods measurement ladder. One Congo is based on ten standard milk tins.';

create table if not exists public.local_measurement_profiles (
  id bigint generated by default as identity primary key,
  code text not null unique,
  display_name text not null,
  kg_per_congo numeric(10,3) not null check (kg_per_congo > 0),
  tins_per_congo numeric(10,2) not null default 10 check (tins_per_congo > 0),
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.local_measurement_profiles is
  'Product-family conversion profiles used later for calculated kg-to-local-measurement ordering.';

create table if not exists public.product_measurement_settings (
  product_id bigint primary key references public.products(id) on delete cascade,
  profile_id bigint not null references public.local_measurement_profiles(id),
  sales_mode text not null default 'fixed_options'
    check (sales_mode in ('fixed_options', 'calculated_input', 'hybrid')),
  calculated_pricing_enabled boolean not null default false,
  base_price_per_kg numeric(12,2) check (base_price_per_kg is null or base_price_per_kg >= 0),
  base_price_source_variant_id bigint references public.product_variants(id) on delete set null,
  fixed_option_discount_enabled boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.product_measurement_settings is
  'Keeps launch sales on fixed options while preserving conversion and base-price metadata for a later calculated-input system.';

insert into public.local_measurement_units
  (code, display_name, congo_multiplier, tin_cup_count, sort_order, notes)
values
  ('half_derica', 'Half Derica', 0.25, 2.5, 10, 'One quarter of a Congo.'),
  ('derica', 'Derica', 0.50, 5, 20, 'One half of a Congo.'),
  ('congo', 'Congo', 1.00, 10, 30, 'Base local measure; also written as Kongo.'),
  ('two_congo', '2 Congo', 2.00, 20, 40, 'Two times the Congo base measure.'),
  ('paint', 'Paint', 3.00, 30, 50, 'Three times the Congo base measure.')
on conflict (code) do update set
  display_name = excluded.display_name,
  congo_multiplier = excluded.congo_multiplier,
  tin_cup_count = excluded.tin_cup_count,
  sort_order = excluded.sort_order,
  is_active = true,
  notes = excluded.notes,
  updated_at = now();

insert into public.local_measurement_profiles
  (code, display_name, kg_per_congo, tins_per_congo, notes)
values
  ('garri_standard', 'Garri Standard', 1.200, 10,
   'Measured standard supplied for all Garri products: 1 Congo equals 1.2kg and 10 standard milk tins.'),
  ('dry_beans_standard', 'Dry Beans Standard', 1.500, 10,
   'Measured standard supplied for dry beans: 1 Congo equals 1.5kg and 10 standard milk tins. Excludes Green Beans, Runner Beans and locust beans.')
on conflict (code) do update set
  display_name = excluded.display_name,
  kg_per_congo = excluded.kg_per_congo,
  tins_per_congo = excluded.tins_per_congo,
  is_active = true,
  notes = excluded.notes,
  updated_at = now();

with garri_profile as (
  select id from public.local_measurement_profiles where code = 'garri_standard'
),
garri_products as (
  select p.id as product_id,
         base_variant.id as source_variant_id,
         base_variant.price as base_price_per_kg
  from public.products p
  left join lateral (
    select pv.id, pv.price
    from public.product_variants pv
    where pv.product_id = p.id
      and pv.is_active = true
      and lower(coalesce(pv.base_unit, '')) = 'kg'
      and pv.base_quantity = 1
      and lower(regexp_replace(trim(coalesce(pv.name, '')), '\\s+', ' ', 'g')) in ('1kg', '1 kg', 'loose kg')
    order by case when pv.purchase_mode = 'fixed' then 0 else 1 end, pv.id
    limit 1
  ) base_variant on true
  where p.is_active = true
    and lower(coalesce(p.name, '')) like '%garri%'
)
insert into public.product_measurement_settings
  (product_id, profile_id, sales_mode, calculated_pricing_enabled,
   base_price_per_kg, base_price_source_variant_id, fixed_option_discount_enabled, notes)
select gp.product_id, gpf.id, 'fixed_options', false,
       gp.base_price_per_kg, gp.source_variant_id, false,
       'Launch mode remains fixed options. Conversion metadata is stored for a later calculated-input rollout.'
from garri_products gp
cross join garri_profile gpf
on conflict (product_id) do update set
  profile_id = excluded.profile_id,
  sales_mode = 'fixed_options',
  calculated_pricing_enabled = false,
  base_price_per_kg = coalesce(public.product_measurement_settings.base_price_per_kg, excluded.base_price_per_kg),
  base_price_source_variant_id = coalesce(public.product_measurement_settings.base_price_source_variant_id, excluded.base_price_source_variant_id),
  fixed_option_discount_enabled = false,
  notes = excluded.notes,
  updated_at = now();

with beans_profile as (
  select id from public.local_measurement_profiles where code = 'dry_beans_standard'
),
bean_products as (
  select p.id as product_id,
         base_variant.id as source_variant_id,
         base_variant.price as base_price_per_kg
  from public.products p
  left join lateral (
    select pv.id, pv.price
    from public.product_variants pv
    where pv.product_id = p.id
      and pv.is_active = true
      and lower(coalesce(pv.base_unit, '')) = 'kg'
      and pv.base_quantity = 1
      and lower(regexp_replace(trim(coalesce(pv.name, '')), '\\s+', ' ', 'g')) in ('1kg', '1 kg', 'loose kg')
    order by case when pv.purchase_mode = 'fixed' then 0 else 1 end, pv.id
    limit 1
  ) base_variant on true
  where p.is_active = true
    and p.product_family = 'Beans and Legumes'
)
insert into public.product_measurement_settings
  (product_id, profile_id, sales_mode, calculated_pricing_enabled,
   base_price_per_kg, base_price_source_variant_id, fixed_option_discount_enabled, notes)
select bp.product_id, bpf.id, 'fixed_options', false,
       bp.base_price_per_kg, bp.source_variant_id, false,
       'Launch mode remains fixed options. Dry-bean conversion excludes fresh Green Beans and Runner Beans.'
from bean_products bp
cross join beans_profile bpf
on conflict (product_id) do update set
  profile_id = excluded.profile_id,
  sales_mode = 'fixed_options',
  calculated_pricing_enabled = false,
  base_price_per_kg = coalesce(public.product_measurement_settings.base_price_per_kg, excluded.base_price_per_kg),
  base_price_source_variant_id = coalesce(public.product_measurement_settings.base_price_source_variant_id, excluded.base_price_source_variant_id),
  fixed_option_discount_enabled = false,
  notes = excluded.notes,
  updated_at = now();

alter table public.local_measurement_units enable row level security;
alter table public.local_measurement_profiles enable row level security;
alter table public.product_measurement_settings enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'local_measurement_units' and policyname = 'public_read_local_measurement_units'
  ) then
    create policy public_read_local_measurement_units
      on public.local_measurement_units for select
      to anon, authenticated
      using (is_active = true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'local_measurement_profiles' and policyname = 'public_read_local_measurement_profiles'
  ) then
    create policy public_read_local_measurement_profiles
      on public.local_measurement_profiles for select
      to anon, authenticated
      using (is_active = true);
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'product_measurement_settings' and policyname = 'public_read_product_measurement_settings'
  ) then
    create policy public_read_product_measurement_settings
      on public.product_measurement_settings for select
      to anon, authenticated
      using (true);
  end if;
end $$;;
