create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  type text,
  route text,
  actor text,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_logs
  add column if not exists type text,
  add column if not exists route text,
  add column if not exists actor text,
  add column if not exists message text,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

update public.admin_logs
set
  type = case
    when coalesce(type, action) in ('admin:error', 'error') then 'error'
    else 'event'
  end,
  route = coalesce(route, entity_type, metadata->>'route'),
  actor = coalesce(actor, metadata->>'actor'),
  message = coalesce(message, metadata->>'message', metadata->>'error', action)
where type is null
   or route is null
   or actor is null
   or message is null;

alter table public.admin_logs
  alter column type set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'admin_logs_type_check'
      and conrelid = 'public.admin_logs'::regclass
  ) then
    alter table public.admin_logs
      add constraint admin_logs_type_check check (type in ('event', 'error'));
  end if;
end $$;

create index if not exists admin_logs_type_created_at_idx
on public.admin_logs (type, created_at desc);
