
CREATE TABLE public.suppliers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  contact_name  text,
  phone         text,
  email         text,
  location      text,
  supplier_type text NOT NULL DEFAULT 'farmer'
                CHECK (supplier_type IN ('farmer','market','wholesaler','processor')),
  produce_notes text,
  is_active     boolean NOT NULL DEFAULT true,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.suppliers IS 'Farmers, markets, and wholesalers Meal05 sources produce from.';
COMMENT ON COLUMN public.suppliers.supplier_type IS 'farmer, market, wholesaler, or processor.';
COMMENT ON COLUMN public.suppliers.location IS 'Farm or market location (area/town).';

CREATE TABLE public.product_suppliers (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint NOT NULL REFERENCES public.products(id)  ON DELETE CASCADE,
  supplier_id bigint NOT NULL REFERENCES public.suppliers(id) ON DELETE CASCADE,
  is_primary  boolean NOT NULL DEFAULT false,
  last_cost   numeric CHECK (last_cost IS NULL OR last_cost >= 0),
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (product_id, supplier_id)
);
COMMENT ON TABLE public.product_suppliers IS 'Which suppliers supply which products, with last known cost price.';
COMMENT ON COLUMN public.product_suppliers.is_primary IS 'Marks the preferred/default supplier for a product.';
COMMENT ON COLUMN public.product_suppliers.last_cost IS 'Most recent purchase cost from this supplier (NGN), for margin tracking.';
CREATE INDEX idx_product_suppliers_product  ON public.product_suppliers(product_id);
CREATE INDEX idx_product_suppliers_supplier ON public.product_suppliers(supplier_id);
;
