create table if not exists public.supplier_variant_prices (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id) on delete cascade,
  cost_price numeric not null check (cost_price >= 0),
  pricing_basis text not null default 'quoted' check (pricing_basis in ('quoted','derived')),
  source_pack_cost numeric null check (source_pack_cost is null or source_pack_cost >= 0),
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (supplier_id, variant_id)
);

comment on table public.supplier_variant_prices is 'Supplier cost mapped to the same sellable product variants customers see. Allows piece, quarter pack, half pack and full pack supplier-cost comparisons.';
comment on column public.supplier_variant_prices.pricing_basis is 'quoted = supplier directly quoted this exact option; derived = proportional cost derived from the quoted source pack.';
comment on column public.supplier_variant_prices.source_pack_cost is 'Supplier quoted cost of the full source carton/bag/box used to derive this option.';

alter table public.supplier_variant_prices enable row level security;

create index if not exists supplier_variant_prices_supplier_idx on public.supplier_variant_prices(supplier_id);
create index if not exists supplier_variant_prices_variant_idx on public.supplier_variant_prices(variant_id);;
