import { NextResponse } from "next/server";
import { z } from "zod";
import { checkRateLimit, applyRateLimitHeaders } from "@/lib/api/rate-limit";
import { isTrustedRequestOrigin } from "@/lib/api/request-origin";
import { getSupabaseAdminClient } from "@/lib/supabase/server-client";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const optionalText=(max)=>z.string().trim().max(max).optional().nullable().transform((value)=>value||null);
const schema=z.object({fullName:z.string().trim().min(2,"Enter your full name.").max(100),email:z.string().trim().email("Enter a valid email address.").max(254).transform(v=>v.toLowerCase()),phone:optionalText(24),city:z.string().trim().min(2).max(80),marketingConsent:z.boolean().default(false),utmSource:optionalText(120),utmMedium:optionalText(120),utmCampaign:optionalText(120)});
export async function POST(request){const limit=await checkRateLimit({request,id:"waitlist",limit:5,windowMs:60000});if(!limit.allowed)return applyRateLimitHeaders(NextResponse.json({error:"Too many attempts. Please try again shortly."},{status:429}),limit);if(!isTrustedRequestOrigin(request))return applyRateLimitHeaders(NextResponse.json({error:"Request origin is not allowed."},{status:403}),limit);try{const parsed=schema.safeParse(await request.json());if(!parsed.success)return applyRateLimitHeaders(NextResponse.json({error:parsed.error.issues[0]?.message||"Check your details and try again."},{status:400}),limit);const d=parsed.data;const{error}=await getSupabaseAdminClient().from("waitlist").insert({full_name:d.fullName,email:d.email,phone:d.phone,country:"NG",city:d.city,source:"landing-page",marketing_consent:d.marketingConsent,consent_at:d.marketingConsent?new Date().toISOString():null,utm_source:d.utmSource,utm_medium:d.utmMedium,utm_campaign:d.utmCampaign});if(error?.code==="23505")return applyRateLimitHeaders(NextResponse.json({message:"You’re already on the list—we’ll keep you posted."}),limit);if(error)throw error;return applyRateLimitHeaders(NextResponse.json({message:"We’ll email you when your early access is ready."},{status:201}),limit)}catch(error){console.error("Waitlist signup failed",error);return applyRateLimitHeaders(NextResponse.json({error:"We couldn’t add you right now. Please try again."},{status:500}),limit)}}
